
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - pwd
  - cd ..
  - git clone git://github.com/AmpersandTarski/ampersand-models.git ampersand-models
  - ls
  - cd ampersand

ghc: 7.8

after_script:
  - cat dist/test/*.log

notifications:
  email:
    recipients:
      - sjcjoosten@gmail.com
      - stef.joosten@tarski.nl
      - michiel.stornebrink@tno.nl
      - han.joosten.han@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

