sudo: false
  # The initial part of this script was inspired by https://github.com/emwap/plugins-multistage/blob/master/.travis.yml
language: c

cache:
  directories:
    - .cabal-sandbox

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.22.4,ghc-7.10.1,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.22,ghc-7.10.2,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.4]}}

  allow_failures:
    - env: CABALVER=1.18 GHCVER=7.8.4
    - env: CABALVER=1.22 GHCVER=7.10.1
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - uname -a

  # The following is to enable tests of Ampersand, while using the ampersand-model directory:
  - pwd
  - cd ..
  - git clone git://github.com/AmpersandTarski/ampersand-models.git ampersand-models
  - ls
  - cd ampersand

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - ghc --info
 - travis_retry cabal update
 - cabal sandbox init
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal build -j2  # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# - cabal install --force-reinstalls dist/*-*.tar.gz
# When there are multiple .tar.gz files, it has to be done somthing like this:
# - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
#   (cd dist && cabal sandbox init --sandbox=../.cabal-sandbox && cabal install -j2 --force-reinstalls "$SRC_TGZ")

after_script:
  - cat dist/test/*.log

notifications:
  email:
    recipients:
      - sjcjoosten@gmail.com
      - stef.joosten@tarski.nl
      - michiel.stornebrink@tno.nl
      - han.joosten.han@gmail.com
