
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - ORIGINALDIR="$(pwd)"
  - cd dontTouch
  - git submodule init
  - git submodule update
  - ls -alrt
  - cd "${ORIGINALDIR}"

ghc: 7.8

after_script:
  - echo "${pwd}"
  - cd dist
  - cd test
  - ls -alrt
  - cat *.log



