
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - ORIGINALDIR="$(pwd)"
  - git clone --bare git://github.com/AmpersandTarski/ampersand-models.git ampersand-models
  - ls -alRt
  - cd "${ORIGINALDIR}"

ghc: 7.8

after_script:
  - echo "${pwd}"
  - cd dist
  - cd test
  - ls -alrt
  - cat *.log



