
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - ORIGINALDIR="$(pwd)"
  - ls dontTouch
  - git submodule init
  - git submodule update
  - ls
  - cd "${ORIGINALDIR}"

ghc: 7.8

