language: haskell

env:
  - GHCVER=7.8.3
  - GHCVER=7.10.1

before_install:
  # (The following is copied from https://github.com/ekmett/lens )
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
      export CABAL=cabal-1.18
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
    fi
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - $CABAL update
  #####

  # The following needs to be teaked some more:
  - sudo apt-get install unixodbc-dev
  - pwd
  - cd ..
  - git clone git://github.com/AmpersandTarski/ampersand-models.git ampersand-models
  - ls
  - cd ampersand


after_script:
  - cat dist/test/*.log

notifications:
  email:
    recipients:
      - sjcjoosten@gmail.com
      - stef.joosten@tarski.nl
      - michiel.stornebrink@tno.nl
      - han.joosten.han@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

