flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HStringTemplate-0.8.3
- JuicyPixels-3.2.6.4
- MissingH-1.3.0.1
- SHA-1.6.4.2
- SpreadsheetML-0.1
- adjunctions-4.2.2
- aeson-0.10.0.0
- aeson-pretty-0.7.2
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.2
- base-orphans-0.4.5
- base64-bytestring-1.0.0.1
- bifunctors-5.1
- binary-search-0.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- cereal-0.5.1.0
- cmark-0.4.1
- cmdargs-0.10.13
- colour-2.3.3
- comonad-4.2.7.2
- conduit-1.2.6
- conduit-extra-1.1.9.2
- connection-0.2.5
- contravariant-1.3.3
- cookie-0.4.1.6
- cryptonite-0.9
- csv-0.1.2
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.1.1.2
- digest-0.0.1.2
- distributive-0.4.4
- dlist-0.7.1.2
- enclosed-exceptions-1.0.1.1
- extensible-exceptions-0.1.1.4
- filemanip-0.3.6.3
- free-4.12.1
- graphviz-2999.18.0.2
- haddock-library-1.2.1
- highlighting-kate-0.6.1
- hourglass-0.2.9
- hslogger-1.2.9
- hslua-0.4.1
- http-client-0.4.26.1
- http-client-tls-0.2.2
- http-types-0.9
- kan-extensions-4.2.3
- lens-4.12.3
- lifted-base-0.2.3.6
- memory-0.10
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- pandoc-1.15.2.1
- pandoc-types-1.12.4.7
- pem-0.2.2
- polyparse-1.11
- prelude-extras-0.4.0.2
- profunctors-5.1.2
- reflection-2
- regex-pcre-builtin-0.94.4.8.8.35
- resourcet-1.1.7
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- simple-sql-parser-0.4.1
- socks-0.5.4
- streaming-commons-0.1.15
- tagged-0.8.2
- tagsoup-0.13.5
- temporary-1.2.0.3
- texmath-0.8.4.1
- tls-1.3.4
- transformers-base-0.4.4
- unix-compat-0.4.1.4
- utf8-string-1.0.1.1
- void-0.7.1
- wl-pprint-1.2
- wl-pprint-text-1.1.0.4
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- xlsx-0.1.2
- xml-1.3.14
- xml-conduit-1.3.2
- xml-types-0.3.6
- yaml-0.8.15.2
- zip-archive-0.2.3.7
resolver: ghc-7.10.3
